---
title: "Figure 4"
output: html_document
---

This notebook creates Fig 4, which displays AE by host-parasite characteristics

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(MCMCglmm)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
options(stringsAsFactors = FALSE)
theme_set(new = theme_bw())
```
```{r importdata}
# focusing only on devo
ae_devo <- read.csv(file = "../data/200421_ArrDevFits_filter.csv", header = TRUE)
dat <- read.csv(file = "../data/main_data_rev.csv", header = TRUE)
tree <- read.tree(file = "../data/full_tree_time_calib.nex")
```
```{r}
dat <- select(dat, tpc_num, binomial = parasite_species, genus, fam = family, order, class, phylum, 
              trait_type, num_temps = num_temps_in_curve, cause_of_repeated_measures, same_experiment,
              measurement_metric, simplified_metric,
              sampling_location_available,
              mean_ann_temp, max_month_temp, min_month_temp,
              latitude, altitude_m, author_latitude, dist_zone,
              habitat,
              plant_anim_parasite, endotherm_in_cycle, stage_in_out_host, target_host)
```
```{r}
ae_devo <- rename(ae_devo, stderr_arr = SE_BA, stderr_ss = SE_SS)
```
```{r}
dat <- left_join(dat, ae_devo, by = 'tpc_num') # join by temperature preference curve identifier
dat <- filter(dat, !is.na(E_Arr)) # remove those without Act E
```
```{r}
dat <- mutate(dat, E_comb = if_else(best_mod2 == "SS", E_SS, E_Arr),
              se_comb = if_else(best_mod2 == "SS", stderr_ss, stderr_arr))
dat <- mutate(dat, global = if_else(dist_zone == 'global', 'global', 'not global'))
```
```{r}
dat <- filter(dat, !(same_experiment == "yes" & simplified_metric != 'mid'), !tpc_num %in% c(61)) # remove non-ind data
```
```{r}
# fix it
tree$tip.label[which(tree$tip.label == "Meloidogyne_hisanica")] <- "Meloidogyne_hispanica"
```

```{r}
spp_not_in_dat <- tree$tip.label[!tree$tip.label %in% dat$binomial] # spp in tree excluded from data
# spp_not_in_dat
```
```{r}
tree_red <- drop.tip(tree, spp_not_in_dat)
```
```{r}
dat$tree_tips <- dat$binomial
```
```{r}
dat <- mutate(dat, mean_ann_temp_cen = mean_ann_temp - median(mean_ann_temp),
              max_month_temp_cen = max_month_temp - median(max_month_temp),
              min_month_temp_cen = min_month_temp - median(min_month_temp))
```
```{r}
# make habitat variable easy to understand
dat <- mutate(dat, habitat_d1 = if_else(habitat == 'terrestrial', 'Terrestrial',
                                        if_else(habitat == 'freshwater' | habitat == 'marine', 'Aquatic', 'NA')))
dat$habitat_d1[which(dat$habitat_d1 == "NA")] <- NA

# sum(is.na(dat$habitat_d))
```
```{r}
dat <- dat%>%mutate(endo_ecto2 = if_else(plant_anim_parasite == "plant", "plant", endotherm_in_cycle))
```


First, we'll make a plot for temperature. To put confidence/credible bands on the plot, we need to refit the model and then extract credible intervals.

```{r}
# new data for preds
p <- data.frame(binomial = dat$binomial[1], 
                tree_tips = dat$tree_tips[1],
                se_comb = quantile(dat$se_comb, probs = 0.05),
                endo_ecto2 = rep(unique(dat$endo_ecto2), 2),
                stage_in_out_host = rep(unique(dat$stage_in_out_host), each = 3),
                pred = "yes")

dat_p <- dat
dat_p$pred <- "no"
dat_p <- bind_rows(dat_p,p)
```
```{r}
tree_red2 <- makeNodeLabel(tree_red) # standardize node labels
Ainv <- inverseA(tree_red2)$Ainv # make inv of phy cov matrix
```
```{r}
prior2<-list(G=list(G1=list(V=1,nu=0.002),
                    G2=list(V=1,nu=0.002),
                    G3=list(V=1,fix=1)), # btw observation variance due to measurement errror/SE of curve fit
              R=list(V=1,nu=0.002)) # uninformative prior for within species effect
```
```{r}
# just mod with temp
mod10 <- MCMCglmm(E_comb ~ endo_ecto2*stage_in_out_host, 
                 random = ~ binomial + tree_tips + idh(se_comb):units, # w/in spp + phylogenetic effx
                 data = dat_p, prior = prior2,
                 nitt=63000, thin = 50,
                 ginverse = list(tree_tips=Ainv),
                 family = "gaussian", pr=F, verbose = F)
```

```{r}
# get predicted values
pdx <- mod10$X # model matrix, just fixed effx
l <- dim(pdx)[1] # number of data points in model
pdx <- pdx[(length(dat$binomial)+1):l,] # restrict to only points where we want preds
num_fe <- mod10$Fixed$nfl # number of fixed effx

# predicted values via matrix multiplication, no taxonomic effx
p_all <- as.matrix(pdx) %*% t(mod10$Sol[,1:num_fe])
# add mean temp to preds, and the make it long
p_all <- bind_cols(select(p, endo_ecto2, stage_in_out_host), data.frame(p_all))
p_all <- p_all%>%
  pivot_longer(cols = c(-endo_ecto2, -stage_in_out_host),
               names_to = "index", values_to = "pred")
# calculate median fit and upper and lower fits for each value of temp
p_all2 <- group_by(p_all, endo_ecto2, stage_in_out_host)%>%
  summarise(fit = median(pred),
            upr = quantile(pred, probs = 0.025),
            lwr = quantile(pred, probs = 0.975))
```



```{r}
f3 <- ggplot(dat, aes(x = endo_ecto2, y = E_comb, color = stage_in_out_host, shape = stage_in_out_host)) +
  geom_crossbar(data = p_all2,
                aes(x = endo_ecto2, y = fit, ymin = lwr, ymax = upr),
                alpha = 0.7, fill = 'lightgrey',
                width = 0.4, fatten = 5,
                position = position_dodge(width = 0.75)) +
  geom_point(aes(size = 1/se_comb),
             position = position_jitterdodge(jitter.width = 0.3),
             alpha = 0.4) +
  scale_y_continuous(breaks = seq(0, 1.5, 0.25)) +
  scale_x_discrete(labels = c("Endotherm\nin cycle","No endotherm\nin cycle", "Plant\nparasite")) +
  scale_shape_discrete(labels = c("In host","Outside host")) +
  scale_color_brewer(type = 'qual', palette = 7, 
                     labels = c("In host","Outside host")) +
  labs(x = NULL, y = "Activation energy (eV)", shape = NULL, color = NULL) +
  guides(size = F) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position = "top")
f3
```

```{r}
fig_w <- 85
fig_h <- 90
```
```{r}
ggsave(f3, filename = "../ms_figs/Fig4X.png", width = fig_w, height = fig_h, units = 'mm')
ggsave(f3, filename = "../ms_figs/Fig4X.svg", width = fig_w, height = fig_h, units = 'mm')
```

